app:
  keycloak:
    url: xxxxxxxxx
    url-admin: xxxxxxxxx
    realms:
      - name: spring-boot-eosc-realm
        client-id: xxxxxxxxx
        client-secret: xxxxxxxxx

server:
  port: 6001
  error:
    include-message: always

logging:
  level:
    ROOT: INFO
    com:
      siseth:
        authorization: DEBUG
    org:
      hibernate:
        SQL: INFO
  file:
    name: logs/authorization.log

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: authentication-service
springdoc:
  api-docs:
    path: /api/access/authentication/v3/api-docs